fix: i3bar and .xinitrc stability

diff --git a/.config/i3blocks/bin/mpc b/.config/i3blocks/bin/mpc
--- a/.config/i3blocks/bin/mpc
+++ b/.config/i3blocks/bin/mpc
@@ -1,6 +1,10 @@
 #!/bin/bash
 set -eEu
 
+if ! command -v mpc >/dev/null; then
+	logger -s "mpc not found. Qutting mpc i3block" >&2
+fi
+
 . "$(dirname "$0")/common_functions"
 
 format='[%artist%: ]%title%'
diff --git a/.config/i3blocks/bin/wifi b/.config/i3blocks/bin/wifi
--- a/.config/i3blocks/bin/wifi
+++ b/.config/i3blocks/bin/wifi
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+if ! command -v iwevent >/dev/null; then
+	logger -s "iwevent was not found. Quitting wifi i3block" >&2
+fi
+
 interval=15
 good_quality=50
 bad_quality=20
